[workspace]
resolver = "3"
members = ["unipipe", "unipipe-macros"]

[package]
name = "unipipe-workspace"
edition = "2024"

[dependencies]
unipipe = { path = "unipipe" }

[dev-dependencies]
futures = "0.3.31"
tokio = { version = "1.45.1", features = ["full"] }
