[package]
name = "unipipe"
version = "0.1.0"
edition = "2024"

[dependencies]
async-stream = "0.3.6"
futures = "0.3.31"
paste = "1.0.15"

[dev-dependencies]
itertools = "0.14.0"
tokio = { version = "1.45.1", features = ["full"] }
